package inventariocentrocomputogui;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
  

    public class FrmInventario extends javax.swing.JFrame {
    ArchivoInventario archivo = new ArchivoInventario();
    DefaultTableModel modelo;
    private int filaEncontrada = -1;

    public FrmInventario() {
        initComponents();
        modelo = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                // NO PERMITE EDITAR EL ID
                return column != 0;
            }
        };
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripción");
        modelo.addColumn("Existencia");
        tblDatos.setModel(modelo);
        cargarTabla();
        txtId.requestFocus();

        habilitarDeshabilitarElimModif(false);
        // SELECCIONAR FILA
        tblDatos.getSelectionModel().addListSelectionListener(e -> {
            int fila = tblDatos.getSelectedRow();
            if (fila >= 0) {
                txtId.setText(tblDatos.getValueAt(fila, 0).toString());
                txtNombre.setText(tblDatos.getValueAt(fila, 1).toString());
                txtDescripcion.setText(tblDatos.getValueAt(fila, 2).toString());
                txtExistencia.setText(tblDatos.getValueAt(fila, 3).toString());
                habilitarDeshabilitarElimModif(true);
            }
        });

        // PINTAR FILAS
        tblDatos.setDefaultRenderer(
                Object.class,
                new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(
                    JTable table,
                    Object value,
                    boolean isSelected,
                    boolean hasFocus,
                    int row,
                    int column) {
                Component c =
                        super.getTableCellRendererComponent(
                                table,
                                value,
                                isSelected,
                                hasFocus,
                                row,
                                column);

                // FILA SELECCIONADA
                if (isSelected) {
                    c.setBackground(Color.CYAN);
                }
                // FILA ENCONTRADA
                else if (row == filaEncontrada) {
                    c.setBackground(Color.YELLOW);
                }
                // NORMAL
                else {
                    c.setBackground(Color.WHITE);
                }
                return c;
            }
        });
    }

    private void habilitarDeshabilitarElimModif(
            boolean estado) {
        btnEliminar.setEnabled(estado);
        btnModificar.setEnabled(estado);
    }
  
   private void limpiarTabla() {
        modelo.setRowCount(0);
    }

    private void limpiarCampos() {
        txtId.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtExistencia.setText("");
        txtId.requestFocus();
        habilitarDeshabilitarElimModif(false);
    }

    private void cargarTabla() {
        limpiarTabla();
        ArrayList<Producto> lista =
                archivo.leerTodos();
        
        for (Producto p : lista) {
            if (p.isEstado()) {
                modelo.addRow(new Object[]{
                    p.getId(),
                    p.getNombre(),
                    p.getDescripcion(),
                    p.getExistencia()
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtExistencia = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 24)); // NOI18N
        jLabel1.setText("INVENTARIO DEL CENTRO DE COMPUTO");

        jLabel2.setText("ID");

        jLabel3.setText("NOMBRE");

        jLabel4.setText("DESCRIPCIÓN");

        jLabel5.setText("EXISTENCIA");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/expediente.png"))); // NOI18N
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.png"))); // NOI18N
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/evaluacion.png"))); // NOI18N
        btnListar.addActionListener(this::btnListarActionPerformed);

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "DESCRIPCION", "EXISTENCIAS"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar)
                            .addComponent(btnModificar))
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnModificar)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnListar)
                                    .addComponent(btnBuscar)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int id =
                Integer.parseInt(txtId.getText());
        Producto existente =
                archivo.buscar(id);
        // SI YA EXISTE
        if (existente != null) {
            JOptionPane.showMessageDialog(
                    this,
                    "El producto ya existe");
            
            for (int i = 0;
                    i < tblDatos.getRowCount();
                    i++) {
                int idTabla =
                        Integer.parseInt(
                                tblDatos.getValueAt(i, 0)
                                        .toString());
                if (idTabla == id) {
                    filaEncontrada = i;
                    tblDatos.setRowSelectionInterval(
                            i,
                            i);
                    tblDatos.scrollRectToVisible(
                            tblDatos.getCellRect(
                                    i,
                                    0,
                                    true));
                    break;
                }
            }
            tblDatos.repaint();
            return;
        }
        // AGREGAR NUEVO
        Producto p = new Producto(
                id,
                txtNombre.getText(),
                txtDescripcion.getText(),
                Integer.parseInt(
                        txtExistencia.getText())
        );
        archivo.agregarProducto(p);
        cargarTabla();
        limpiarCampos();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int id =
                Integer.parseInt(txtId.getText());
        if (archivo.eliminar(id)) {
            JOptionPane.showMessageDialog(
                    this,
                    "Eliminado");
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "No encontrado");
        }
        cargarTabla();
        limpiarCampos();
        filaEncontrada = -1;
        tblDatos.repaint();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int fila =
                tblDatos.getSelectedRow();

        // MODIFICAR DESDE TABLA
        if (fila >= 0) {
            int id = Integer.parseInt(
                    tblDatos.getValueAt(fila, 0)
                            .toString());
            String nombre = tblDatos.getValueAt(fila, 1).toString();
            String descripcion = tblDatos.getValueAt(fila, 2).toString();

            int existencia = Integer.parseInt(tblDatos.getValueAt(fila, 3).toString());
            boolean ok = archivo.modificar(
                    id,
                    nombre,
                    descripcion,
                    existencia);
            JOptionPane.showMessageDialog(
                    this,
                    ok
                    ? "Modificado desde tabla"
                    : "No encontrado");
            cargarTabla();
            filaEncontrada = -1;
            tblDatos.repaint();
        }
        // MODIFICAR DESDE TEXTBOX
        else {
            int id =
                    Integer.parseInt(
                            txtId.getText());
            boolean ok = archivo.modificar(
                    id,
                    txtNombre.getText(),
                    txtDescripcion.getText(),
                    Integer.parseInt(
                            txtExistencia.getText())
            );
            JOptionPane.showMessageDialog(
                    this,
                    ok
                    ? "Modificado"
                    : "No encontrado");
            cargarTabla();
            limpiarCampos();
            filaEncontrada = -1;
            tblDatos.repaint();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        String idBuscar =txtId.getText();
        if (idBuscar.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No puedes dejar campos vacíos");
            txtId.requestFocus();
        } else {
            int id =
                    Integer.parseInt(idBuscar);
            Producto p =
                    archivo.buscar(id);
            if (p != null) {
                txtNombre.setText(p.getNombre());
                txtDescripcion.setText(p.getDescripcion());
                txtExistencia.setText(String.valueOf(p.getExistencia()));
                habilitarDeshabilitarElimModif(true);
                // BUSCAR FILA
                for (int i = 0;i < tblDatos.getRowCount();i++) {
                    int idTabla =Integer.parseInt(tblDatos.getValueAt(i, 0).toString());

                    if (idTabla == p.getId()) {
                        filaEncontrada = i;
                        tblDatos.setRowSelectionInterval(
                                i,
                                i);
                        tblDatos.scrollRectToVisible(
                                tblDatos.getCellRect(
                                        i,
                                        0,
                                        true));
                        break;
                    }
                }
                tblDatos.repaint();
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "No encontrado");
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        cargarTabla();
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {

        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmInventario().setVisible(true));
  }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

}
